app/urls.py
from django.urls import path
from app import views

app_name = "app"
urlpatterns = [
    path("", views.top, name="index"),
    path("detail/<int:city_id>", views.detail, name="detail"),
]

project/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", include("app.urls"))
]

app/models.py
from django.db import models


class City(models.Model):
    """場所"""

    name = models.CharField("name", max_length=20)

    def __str__(self):
        return self.name


class Week(models.Model):
    """週情報"""

    city_id = models.IntegerField("city_id", unique=True)
    order = models.IntegerField("order")
    sunday = models.IntegerField("sunday")
    monday = models.IntegerField("monday")
    tuesday = models.IntegerField("tuesday")
    wednesday = models.IntegerField("wednesday")
    thursday = models.IntegerField("thursday")
    friday = models.IntegerField("friday")
    saturday = models.IntegerField("saturday")

    def __str__(self):
        return f"{self.sunday} {self.monday} {self.tuesday} {self.wednesday} {self.thursday} {self.friday} {self.saturday}"

app/views.py
from django.shortcuts import render
from .models import City, Week


def top(request):
    """トップページ"""
    message = {"title": "top"}
    return render(request, "index.html", message)


def detail(request, city_id):
    """詳細"""
    city = City.objects.get(pk=city_id)
    week = Week.objects.get(city_id=city.pk)
    forecasts = [
        week.sunday,
        week.monday,
        week.tuesday,
        week.wednesday,
        week.thursday,
        week.friday,
        week.saturday,
    ]
    day_of_weeks = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
    message = {
        "title": city.name,
        "forecasts": forecasts,
        "day_of_weeks": day_of_weeks,
    }
    return render(request, "detail.html", message)

app/templates/base.html
{% load static %} {% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>{{title}}</title>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% bootstrap_css %} {% bootstrap_javascript %}
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}" />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'app:index' %}">weather-django</a>
      </div>
    </nav>
    <div class="container container-lg">
      {% block content %} {% endblock content %}
    </div>
  </body>
</html>

app/templates/detail.html
{% extends 'base.html' %} {% block content %}
<div>
  <h3>{{title}}</h3>
  <table class="table table-bordered table-responsive-sm">
    <thead>
      <tr class="text-center">
        {% for day in day_of_weeks %}
        <th>{{day}}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for forecast in forecasts %}
        <td class="text-center">
          {% if forecast == 1 %}
          <span class="material-symbols-outlined"> cloud </span>
          {% elif forecast == 2 %}
          <span class="material-symbols-outlined text-primary">
            beach_access
          </span>
          {% else %}
          <span class="material-symbols-outlined text-danger"> sunny </span>
          {% endif %}
        </td>
        {% endfor %}
      </tr>
    </tbody>
  </table>
  <a href="{% url 'app:index' %}">戻る</a>
</div>
{% endblock content %}

app/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm">
      <a href="{% url 'app:detail' city_id=1 %}">東京</a>
    </div>
    <div class="col-sm">
      <a href="{% url 'app:detail' city_id=2 %}">大阪</a>
    </div>
    <div class="col-sm">
      <a href="{% url 'app:detail' city_id=3 %}">福岡</a>
    </div>
  </div>
</div>
{% endblock content %}